### ISSUE TITLE
v2.0.x containerd docker remote bug: sometimes gets "cannot reuse body, request must be retried"

### ISSUE THREAD

**Issue by thockin** [estesp/manifest-tool#122] opened 2021-06-24 03:32 UTC
```
manifest-tool                                         \
    --username=oauth2accesstoken                      \
    --password=$(gcloud auth print-access-token)     \
    push from-args                                    \
    --platforms "$platforms"                         \
    --template gcr.io/k8s-staging-git-sync/git-sync:v3.3.3__OS_ARCH \
    --target gcr.io/k8s-staging-git-sync/git-sync:v3.3.3
FATA[0004] Error pushing manifest list/index to registry: sha256:343fd4cd9582fc02b98d6641aa29356d5986ab1a31de5c5b1d0080815e083cbe: failed commit on ref "manifest-sha256:fcb67f390ed38b64a54c7c26bb72c3494d6c269c7389add0448d0dde8b510d58": cannot reuse body, request must be retried 
```

Syncing to v1.0.3 works, but since this doesn't use go modules, that's a PITA :)

**Comment by estesp** [comment] 2021-06-24 14:21
Hmm, strange. I tested v2.0.0-beta.0 with GCR, but my normal test image uses repos not tags for differentiating the platforms. I'll have to test with tags in case that changes behavior in some way.

Just tried again to make sure:
```
$ ./manifest-tool --version
./manifest-tool version 2.0.0-beta.0 (commit: ff5aefe0f43b89efc21373c5514ef98a62c63e8a)
[long push from-args command]
.... response.status="201 Created" size=966 url="https://gcr.io/v2/[REDACTED]/alpine/manifests/latest"
Digest: sha256:493661ff8ba145bbe641dc56c6da3071b7761dbb22cd42fdf15b31b6f170eaa8 966

**Comment by estesp** [comment] 2021-09-15 16:40
Any chance you've been able to try this again? Especially now that maybe you are using v2 :) I have never been able to reproduce an issue pushing to GCR.

**Comment by thockin** [comment] 2021-09-15 17:24
I have  not had need to push a manifest lately, but I will try to fake one
up and let you know.

**Comment by estesp** [comment] 2022-02-14 20:36
Just released v2.0.0 and it seems to be working fine with GCR in my tests. Going to close this for now but feel free to re-open if you are able to reproduce.

**Comment by thockin** [comment] 2022-03-11 17:44
I'm baaaaaack

```
platforms=$(echo linux/amd64 linux/arm linux/arm64 linux/ppc64le linux/s390x | sed 's/ /,/g');  \
manifest-tool                                         \
    --username=oauth2accesstoken                      \
    --password=$(gcloud auth print-access-token)     \
    push from-args                                    \
    --platforms "$platforms"                         \
    --template gcr.io/k8s-staging-git-sync/git-sync:v3.5.0__OS_ARCH \
    --target gcr.io/k8s-staging-git-sync/git-sync:v3.5.0
FATA[0004] Error pushing manifest list/index to registry: sha256:98821a216b62b6ee5dccdc2682c87f85d64e905d61872d0ab19073f9c4463623: failed commit on ref "manifest-sha256:6850b0792b249e2562a2b622e1938cb35747174030aef27d5274319811d9f150": cannot reuse body, request must be retried 
```

I have no idea where to even start

**Comment by thockin** [comment] 2022-03-11 18:05
FWIW manifest-tool 1.0.3 still works:

```
platforms=$(echo linux/amd64 linux/arm linux/arm64 linux/ppc64le linux/s390x | sed 's/ /,/g');  \
manifest-tool                                         \
    --username=oauth2accesstoken                      \
    --password=$(gcloud auth print-access-token)     \
    push from-args                                    \
    --platforms "$platforms"                         \
    --template gcr.io/k8s-staging-git-sync/git-sync:v3.5.0__OS_ARCH \
    --target gcr.io/k8s-staging-git-sync/git-sync:v3.5.0
Digest: sha256:d16f5b2bca94cdbb4e40b256bfe639450a6f0577dbd8b3fcaf126a2261822fcd 1665
```

**Comment by estesp** [comment] 2022-03-11 20:27
You may not be alone; looks like this might be a codepath my testing just isn't hitting (and we have a recent report in [containerd proper](https://github.com/containerd/containerd/issues/5978) as well); also https://github.com/estesp/manifest-tool/issues/156#issuecomment-1062647604

In the #156 issue, I see a 404 response that my tries with Quay aren't getting, and that potentially **is** trying to reuse the body on the response asking for auth? Need to dig deeper now that it doesn't seem to be a random one-off.

**Comment by thockin** [comment] 2022-03-11 23:09
Let me know if I can help with debug traces or something...

**Comment by estesp** [comment] 2022-03-14 17:22
Thanks; just found a reproduce scenario and found that, aside from the fact containerd is working on fixing the "body reuse" problem, there is a different flow of registry interaction when the source repos are != target repo (e.g. use "names" not "tags" to differentiate OS/arch).

When all source images are in the same repo namespace as the target manifest list, that flow ends in a 404 existence check on the final target `name:tag` which appears to cause a `401 Unauthorized`, which leads to the retry with same body error in the auth flow. Digging into that now; I think it's related to registry token scopes (which are set at the library/auth level, not in my code, but need to find out why it's causing different behavior)

**Comment by thockin** [comment] 2022-03-15 19:31
Works for me, commented in #159

**Closed** 2022-03-15 20:52 UTC

**Comment by thockin** [comment] 2022-10-11 08:31
will try
